### ISSUE TITLE
[Minor] Unable to close out of Spells

### ISSUE THREAD

**Issue by leemeli** [I461-Bridge/Level#12]
Reproduction:
Select Bard class level 6
Press "Next Page"
Press "Next"
Press "Next Page"
Press "Next Page"
Click "Spells: Level 1"
Click "Charm Person" or any other spell
Unable to close it, can open more spells while that spell is still open

**Comment by isabelgiang** [comment]
Hey! Thanks for your feedback! 
Were you able to close the spell description by clicking on the button for the spell a second time? I understand that the size of the tooltip, along with its position not following the movement of its corresponding button makes it very difficult to close, but it should still be close-able.

**Comment by leemeli** [comment]
I just tried that and it does work, unless I click on another spell and it opens another tooltip that covers it.
