### ISSUE TITLE
Layering spell descriptions

### ISSUE THREAD

**Issue by jkuelz** [I461-Bridge/Level#16]
Unable to close spell descriptions once open, thus causing them to layer on top of one another.
1. Select class level Bard.
2. Select level 8 (or any other level it seems).
3. Click GO.
4. Click Next.
5. Click Next.
6. Click Next.
7. Click "Spells level 1"
8. Select at least 3 spells (I chose "Charm Person", "Comprehend Languages", "Disguise Self", and "Identify).
**Problem:** Unable to close the descriptions and the layering makes some impossible to read.

**Comment by isabelgiang** [comment]
As this issue is caused by the overlay of the spell tooltips, I've marked this as a duplicate of #12. Issue was solved by merging #24.
