### ISSUE TITLE
Can't navigate due to spell tooltips covering buttons 

### ISSUE THREAD

**Issue by yipang** [I461-Bridge/Level#17]
In the Step page, I can't go next or go back, since I clicked two selections, eg "mage hand" and "minor illusion". These two windows cannot be closed since the original section button is covered by these two new windows, also the next and back button.

**Comment by isabelgiang** [comment]
As this issue is caused by the overlay of the spell tooltips, I've marked this as a duplicate of #12. Issue was solved by merging #24.
