### ISSUE TITLE
[Major] Page stuck on the loading screen

### ISSUE THREAD

**Issue by johnyunjr** [I461-Bridge/Level#20]
After choosing a certain class and level:
- Class: Druid
- Level: 11, 13, 15, or 17

1. It takes me to 'Step 1: Increase Hit Points' page. 

2. Once I hit 'Next Page,' it stays on the loading screen indefinitely for each of the listed levels mentioned above.

This inhibits the progress of the player for the Druid class.

**Comment by sopheakneak** [comment]
Whoa, good find! Thanks! We got it fixed up!
